app/controllers/pages_controller.rb
app/views/layouts/application.html.erb
app/views/layouts/shared/_ footer.html.erb
app/views/pages/home.html.erb
db/schema.rb

* Pages controller > Added home page + legal page methods
* Added footer partial file placeholder (empty)
* Added home view placeholder

Homepage / footer initialization

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_index.scss
app/views/layouts/application.html.erb
app/views/layouts/shared/_ footer.html.erb
app/views/shared/_footer.html.erb
config/routes.rb

* Footer basis
* Added all standard css files in stylesheets folder, e.g. bootstrap variables, colors, fonts, etc.

Footer & general styling setup

---

app/assets/stylesheets/config/_colors.scss

I added the buddy-boost color pallette to the color scss file

color pallette

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_legal.scss
app/views/pages/legal.html.erb

* Setup legal page
* Added Privacy Policy text + first styling (can always edit later to make it more flashy - drop down text for each header would be amazing 💯  - will add to backlog)

Legal page

---

app/views/pages/legal.html.erb

* Fixed one paragraph that I forgot to end :')

Legal page - fixed typo and end sentence

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_index.scss
app/controllers/pages_controller.rb
app/views/pages/profile.html.erb

* Added controller method for profile page `/profile`
* Added bare bones of profile page, will make it nice tomorrow :)
* Added standard avatar classes everyone can use - see stylesheets > components > avatar

Profile page layout + avatar component

---

db/migrate/20240305190424_add_deadline_column_to_goals.rb
db/schema.rb

- migration file added to add deadline column into goals table.

add deadline column to the goals table

---

app/views/shared/_footer.html.erb
db/seeds.rb

* Edited link in footer for 'sign up'. That's it 💯

fix link footer sign up

---

app/controllers/goals_controller.rb
app/views/goals/index.html.erb
app/views/goals/new.html.erb
app/views/goals/show.html.erb

goals controller new&create function completed

AllisonXuanChen/ goals controller new&create

---

app/assets/stylesheets/components/_background-card.scss
app/assets/stylesheets/components/_index.scss
app/controllers/pages_controller.rb
app/views/devise/registrations/edit.html.erb
app/views/pages/profile.html.erb

* Possibility to edit username, name & password implemented
* Form styling 
* Added general class 'blue-background' if you want a light blue background. Might be nice for other forms as well; if you want to use it and have trouble, let me know :-)

Update user info - form & style

---

app/controllers/goals_controller.rb
app/views/goals/_new-goal.html.erb
app/views/goals/index.html.erb
app/views/layouts/application.html.erb
config/routes.rb

- delete /goals/new route 
- added new goal form as a modal on goals page

implement new goal model on goals page

---

app/views/pages/profile.html.erb
app/views/shared/_navbar.html.erb

I changed avatar in to something very inclusive, some thumbs with smiles :)

changed avatar

---

app/controllers/application_controller.rb

when you sign in you go to profile page

now when you sign in you go straight to the profile

---

app/views/goals/index.html.erb
app/views/goals/show.html.erb

Small thing, added if someone comes on an empty page

empty goals view pages

---

app/assets/stylesheets/components/_avatar.scss
app/views/shared/_match-card.html.erb

Heiddis' nice avatars were not yet in the match card, so added them there too :)

Fix avatar matchcard

---

app/assets/stylesheets/pages/_log-in.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

fixed both sign up and sign in form

log in and sign up form style

---

app/assets/stylesheets/components/_background-card.scss
app/controllers/pages_controller.rb
app/views/matches/show.html.erb
app/views/shared/_match-card.html.erb

* Added styling to buddy dashboard :)
* Avatars might be identical due to issue, see other PR for fix on that :)

Buddy dashboard - first styling done 

---

app/views/devise/registrations/new.html.erb

removed the sign in button from the sign up form

removed the sign in button

---

app/models/match.rb
app/views/matches/show.html.erb
app/views/shared/_match-card.html.erb

We got the same avatars sometimes, because sometimes you are current_user ánd matched_user at the same time. I found this solution with the help of Daniele! 
The fix affects the avatars on the buddy dashboard & profile page.

Avatar fix w/matched_user difficulties

---

app/controllers/goals_controller.rb

A tiny fix on goals controller to change redirect link after goal creation to ->  ` redirect_to profile_path`

update goal controller

---

app/assets/stylesheets/pages/_log-in.scss
app/assets/stylesheets/pages/_sign-up.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

made background for the log in and sign up page and made the log in form bigger

log in form wider and background of log in and sign up form added

---

app/views/shared/_footer.html.erb

Footer had a bunch of margin below, removed that. Now it's really at the bottom of the page!

Footer made sticky

---

app/assets/stylesheets/components/_alert.scss
app/assets/stylesheets/components/_index.scss
app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb

yayyyyyyyy cute little alert when you sign up- sign in and sign up

alert when signed in and out and signed up

---

Gemfile
Gemfile.lock
db/seeds.rb

Nothing new, just added more users and unmatched goals

add more seed data

---

app/assets/stylesheets/components/_alert.scss
app/assets/stylesheets/components/_index.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/shared/_flashes.html.erb
config/environments/development.rb
db/schema.rb

flashes fixed for the page and now we are able to sign up as well, there was some problem with turbo that me and Eoan fixed :)

flashes and sign up fixed

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_profile-tabs.scss
app/assets/stylesheets/pages/_profile.scss
app/views/pages/profile.html.erb
app/views/shared/_add-goal-modal.html.erb
app/views/shared/_match-card.html.erb
app/views/shared/_profile-card.html.erb
app/views/shared/_profile-tabs.html.erb
db/schema.rb

* Added tabs interface to profile page to switch from profile, goals, matches + achievements
* To improve readability of profile page html, added partials for goal modal/button & profile-card
* Achievements is empty for now, separate ticket 
* Did some styling, will do more if there's time
* Will edit match button in separate PR

Profile page - tabs working!

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_profile-tabs.scss
app/assets/stylesheets/pages/_profile.scss
app/views/matches/show.html.erb
app/views/pages/profile.html.erb
app/views/shared/_add-goal-modal.html.erb
app/views/shared/_edit-match-form.html.erb
app/views/shared/_goal-card.html.erb
app/views/shared/_match-card.html.erb
app/views/shared/_profile-card.html.erb
app/views/shared/_profile-tabs.html.erb
db/schema.rb

Buttons: 
* Removed complete goal button
* Styling "edit buddy status button" > in style of previous "complete goal button" 
Update "edit-buddy-status" form:
* as status options only completed or cancelled (so no "in progress")
* comment text field for reason of cancellation/completion

Dashboard > edit match status button + form

---

app/assets/stylesheets/pages/_profile.scss
app/controllers/goals_controller.rb
app/views/goals/edit.html.erb
app/views/pages/profile.html.erb
app/views/shared/_edit-goal-form.html.erb
app/views/shared/_edit-goal-modal.html.erb
app/views/shared/_goal-card.html.erb
config/routes.rb

* Edit/update goal routes added in **routes.rb** 
* Edit/update goal methods added in goal **controller**
* **Edit button** on goal card works now - you can edit your goal. Form is identical to add-goal-form.
* Added **HTML partials** to ensure readability of profile page view + goal card partial

Edit goal functionality + frontend

---

app/controllers/pages_controller.rb
app/models/goal.rb
app/views/pages/my_achievements.html.erb
config/routes.rb

Achievement page

---

app/assets/stylesheets/pages/_profile.scss
app/controllers/goals_controller.rb
app/views/goals/edit.html.erb
app/views/layouts/application.html.erb
app/views/shared/_goal-card.html.erb
config/routes.rb

* Added delete route
* Added delete method to goals controller
* Added delete button (trash can) to goal card html partial 
* Included feathericon compatibility to use their icons next to fontawesome

Delete goal functionality & front-end

---

app/assets/stylesheets/components/_profile-tabs.scss
app/views/shared/_profile-tabs.html.erb

* Very small changes to font/button-size of tabs profile page.

Profile page tabs styling

---

app/views/matches/show.html.erb
db/schema.rb

Chat button fixed 

---

app/controllers/pages_controller.rb
app/views/pages/home.html.erb
db/schema.rb

fixes to the total buddies on the achievement page

tweaks to the achievements

---

app/assets/stylesheets/pages/_profile.scss
app/controllers/pages_controller.rb
app/views/pages/_achievements.html.erb
app/views/pages/profile.html.erb

Text for profile-match-tab when there are no matches (yet)

---

app/assets/stylesheets/pages/_profile.scss
app/views/pages/_achievements.html.erb

Achievements tab (done)

---

app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links-loginform.html.erb

Removed 2nd login-link from login form 

---

app/controllers/goals_controller.rb
app/views/shared/_edit-goal-form.html.erb
app/views/shared/_edit-goal-modal.html.erb
config/routes.rb

* fixed modal; unique ID required for each goal card so added pe-tag with goal id in the id of the modal/modal-button

edit goal button/modal fixed

---

app/assets/stylesheets/pages/_profile.scss
app/controllers/goals_controller.rb
app/views/pages/_achievements.html.erb
app/views/shared/_edit-goal-form.html.erb
app/views/shared/_edit-goal-modal.html.erb
config/routes.rb

Achievements styling signin-amount

---

app/assets/stylesheets/components/_avatar.scss
app/views/matches/show.html.erb
app/views/shared/_match-card.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_profile-card.html.erb

* Fixed issue with resizing avatars when personal photo was uploaded
* Made avatar styling more DRY, no in-line styling for each avatar required anymore

Avatar sizes fix

---

app/assets/stylesheets/components/_alert.scss
app/controllers/application_controller.rb
app/controllers/goals_controller.rb
app/controllers/matches_controller.rb
app/javascript/controllers/backdrop_alert_controller.js
app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb
app/views/shared/_goal-card.html.erb
db/seeds.rb

flashes to matches and goals, they look like this:

Flashes goals matches

---

app/assets/stylesheets/pages/_buddydashboard.scss
app/views/matches/show.html.erb
app/views/pages/profile.html.erb
app/views/shared/_task-list.html.erb

* Scrollable tasks on dashboard if there are (too) many
* Fixed height issue re: columns

Scrollable tasks on dashboard

---

app/assets/stylesheets/pages/_buddydashboard.scss
app/views/matches/show.html.erb

Progress bar dashboard

---

app/views/matches/show.html.erb

progressbar fixed :)

---

app/assets/stylesheets/components/_background-card.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_buddydashboard.scss
app/assets/stylesheets/pages/_profile.scss
app/views/matches/show.html.erb
app/views/pages/_achievements.html.erb
app/views/shared/_banner.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_new-task.html.erb
app/views/shared/_profile-card.html.erb
app/views/shared/_task-list.html.erb

-  **DONE** change background color of tasks
-  **DONE** make login and signup buttons a bit softer, so main call to action is on focus on landing page
-  **DONE** 1 pencil icon is enough in profile tab to edit profile -> maybe we can keep only the on avatar
-  **DONE** update task descripiton -> What do you want to add?? or sth like that
-  **DONE** Add emojies somewhere next to completed goals or drop goals
-  **DONE** go to buddy chat => talk to your buddy
still to do:
- direct to active tab on profile
- landing page: how it works texts are not aligned
- goal create model X -> overwrite on bootstrap

Lastminute fixes - part 1

---

app/assets/stylesheets/components/_alert.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_profile.scss
app/controllers/goals_controller.rb
app/controllers/matches_controller.rb
app/javascript/controllers/backdrop_alert_controller.js
app/views/matches/show.html.erb
app/views/pages/_achievements.html.erb
app/views/shared/_add-goal-modal.html.erb
app/views/shared/_edit-goal-form.html.erb
app/views/shared/_edit-goal-modal.html.erb
app/views/shared/_edit-match-form.html.erb
app/views/shared/_flashes.html.erb
app/views/shared/_goal-card.html.erb
app/views/shared/_new-goal.html.erb
app/views/shared/_new-task.html.erb

If statement re: empty tasks buddy

---

app/assets/stylesheets/components/_alert.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_profile.scss
app/controllers/goals_controller.rb
app/controllers/matches_controller.rb
app/javascript/controllers/backdrop_alert_controller.js
app/views/matches/show.html.erb
app/views/pages/_achievements.html.erb
app/views/shared/_add-goal-modal.html.erb
app/views/shared/_edit-goal-form.html.erb
app/views/shared/_edit-goal-modal.html.erb
app/views/shared/_edit-match-form.html.erb
app/views/shared/_flashes.html.erb
app/views/shared/_goal-card.html.erb
app/views/shared/_new-goal.html.erb
app/views/shared/_new-task.html.erb

* Flash colors
* Flashes text edit
* Icon navbar fix
* Close buttons on modals
* Modal & form finetuning, added labels etc.
* Edit goal form styling issue w/font-size fixed

Final fixes part 2

---

app/controllers/pages_controller.rb
app/views/pages/legal.html.erb

Privacy page access / wording

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

homepage update

---

app/assets/stylesheets/pages/_buddydashboard.scss
app/views/matches/show.html.erb
app/views/shared/_task-list.html.erb

Fix task alignment on buddy dashboard

---

app/views/matches/show.html.erb

* Added the "chat with your buddy!" text on button also to if in if/else statement, so same text shows always on button

Chat button fixed

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/pages/_buddydashboard.scss
app/views/matches/show.html.erb

Separate cancel & complete btn

---

app/views/matches/show.html.erb

fix buttons dashboard margins
